<!-- Generated by Forge -->

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>

<form:form commandName="@{ccEntity}">

	<form:hidden path="id"/>
	<form:hidden path="version"/>

	@{metawidget}

	<span class="buttons">
		<input type="submit" value="Save" class="btn btn-primary"/>
		<a class="btn btn-primary" href="<c:url value="@{targetDir}@{entityPlural.toLowerCase()}"/>">Cancel</a>
	</span>
</form:form>
