<!-- Generated by Forge -->

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div class="main">
	<p style="text-align: right; padding-top: 150px">
		<a target="_blank" href="http://www.jboss.org"><img
			src="<c:url value="/static/resources/jboss-community.png"/>"
			alt="JBoss and JBoss Community" width="250" height="31" border="0">
		</a><br />To replace this page, edit 'src/main/webapp/WEB-INF/views/error.jsp', or
		keep Forging!
	</p>
</div>