<!-- Generated by Forge -->

<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

<div class="main">
	<h2 class="success">
		"Your application is running."
	</h2>
	<p>
		<a target="_blank" href="https://docs.jboss.org/author/display/FORGE">Documentation</a> | 
		<a target="_blank" href="http://twitter.com/intent/tweet?text=I+just+built+and+deployed+a+webapp+using+%23Forge,+from+%23JBoss+-+Super+easy!+(+http://jboss.org/forge+)">
		Get Excited!</a><br />
		<a target="_blank" href="http://jboss.org/forge"><br />Forge Project</a> | 
		<a target="_blank" href="https://lists.jboss.org/mailman/listinfo/forge-users">User List</a> | 
		<a target="_blank" href="https://issues.jboss.org/browse/FORGE">Report an issue</a>
	</p>
</div>
